//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StRegisteredCours
    {
        public System.Guid CourseRegistrationId { get; set; }
        public System.Guid CourseId { get; set; }
        public System.Guid StudentID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
